data/urls.py
from django.urls import path,re_path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('apparatus/', views.ApparatusListView, name='apparatus'),
    path('apparatus/<int:apparatus_pk>/', views.ApparatusDetailView, name='apparatus-detail'),
    path('apparatus/<int:apparatus_pk>/upload_xlsx/', views.upload_xlsx, name='upload_xlsx'),
    path('test/<int:test_pk>/', views.TestView, name='test'),
    path('test/<int:test_pk>/upload_csv/', views.upload_csv, name='upload_csv'),
    path('run/<int:run_pk>', views.ViewRun, name='run-detail'),
    path('diagnostic/<int:diagnostic_pk>', views.ViewDiagnostic, name='diagnostic-detail'),
    path('cathode/<int:cathode_pk>', views.CathodeView, name='cathode-detail'),
    path('nozzle/<int:nozzle_pk>', views.NozzleView, name='nozzle-detail'),
    path('condition/<int:condition_pk>', views.ConditionView, name='condition-detail'),
    path('disk/<int:disk_pk>', views.DiskView, name='disk-detail'),
    path('run/<int:run_pk>/download_csv/', views.DownloadRunCSV, name='run-detail-csv'),

    path('search/', views.SearchView, name='search'),
    path('search/<int:apparatus_pk>/', views.SearchData, name='search-app'),
    path('search/<int:apparatus_pk>/download_csv/', views.DownloadSearchCSV, name='search-csv'),	
]

mARC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
admin.site.site_header = "mARC Database Admin v1.0"

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('data/', include('data.urls')),
    path('pdf/', include('pdfs.urls')),
    path('', RedirectView.as_view(url='/data/', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

data/models.py
from django.db import models
import pandas as pd
import numpy as np

from units.models import ComboUnit
# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=50,unique=True)
    notes= models.TextField(null=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = "People"

class Apparatus(models.Model):
    name = models.CharField(max_length=200,unique=True)
    acronym = models.CharField(max_length=10,unique=True)
    notes = models.TextField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['pk']
        verbose_name_plural = "Apparatus"

class Test(models.Model):
    name = models.CharField(max_length=200,unique=True)
    date = models.DateField()
    notes = models.TextField(null=True)
    apparatus = models.ForeignKey(Apparatus, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['date']


class Run(models.Model):
    name = models.CharField(max_length=200)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    date = models.DateTimeField(null=True)
    test_engineer = models.ForeignKey(Person, null=True, on_delete=models.SET_NULL,related_name = "test_engineer")
    principle_investigator = models.ForeignKey(Person, null=True, on_delete=models.SET_NULL, related_name = "principle_investigator")
    operator = models.ForeignKey(Person, null=True, on_delete=models.SET_NULL,related_name = "operator")
    objective = models.TextField(null=True,blank=True)
    procedure = models.TextField(null=True,blank=True)
    nozzle = models.ForeignKey('system.Nozzle',null=True,on_delete=models.SET_NULL)
    cathode = models.ForeignKey('system.Cathode', on_delete=models.SET_NULL, null=True)
    disks = models.ManyToManyField('system.Disk', blank=True)
    diagnostics = models.ManyToManyField('Diagnostic')
    notes = models.TextField(null=True,blank=True)
    
    class Meta:
        unique_together = (("name", "test"),)
        ordering = ['-date']
    
    def __str__(self):
        return self.name

    # def get_dataframe(self):
    #     series = Series.objects.filter(run=self)
    #     col_data, col_names = [],[]
    #     for s in series:
    #         col_names.append(s.diagnostic.name)
    #         col_data.append( s.record_set.order_by('index').values_list('value',flat=True) )
    #     d = np.array( col_data ).T
    #     return pd.DataFrame(d,columns=col_names)

    def get_dataframe(self):
        series = DiagnosticSeries.objects.filter(run=self)
        col_data, col_names = [],[]
        timelabel = "Time [s]"

        ### Check if more than one time series
        q_ts = TimeSeries.objects.filter(diagnosticseries__run =self).distinct()
        if len(q_ts)==1:
            col_names.append(timelabel)
            col_data.append(q_ts[0].time)
            for s in series:
                col_names.append(s.diagnostic.name)
                col_data.append( s.values )
        else:
            for s in series:
                col_names.append(timelabel)
                col_data.append( s.time.time )
                col_names.append(s.diagnostic.name)
                col_data.append( s.values )
        d = np.array( col_data ).T
        
        return pd.DataFrame(d,columns=col_names)
        
    def get_diagnostics(self):
        dg_list = DiagnosticSeries.objects.filter(run=self).values_list('diagnostic__name',flat=True)
        diagnostics = Diagnostic.objects.filter(name__in=dg_list,apparatus=self.test.apparatus)
        return diagnostics

class Diagnostic(models.Model):
    name = models.CharField(max_length=50)
    units = models.ForeignKey(ComboUnit, on_delete=models.CASCADE)
    apparatus = models.ForeignKey(Apparatus, on_delete=models.CASCADE)
    notes = models.TextField(blank=True,null=True)
    sensor= models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True)
    datasheet = models.FileField(null=True, blank=True)
    flag_if_missing = models.BooleanField(null=True, blank=True, default=False)
    is_input_setting = models.BooleanField(default=False)

    DATATYPES = [
        ('IMAGE', 'Image'),
        ('VIDEO', 'Video'),
        ('XT','Time series'),
        ('XYT', 'N-dim time series'),
        ('LIDAR', 'Point cloud'),
        ('OTHER', 'Other'),
    ]

    TYPES = [
        ('SYSTEM', 'System'),
        ('ENVIRN', 'Environmental'),
        ('CAMERA', 'Camera'),
        ('INSERT', 'Insertion'),
        ('OTHER', 'Other'),
    ]
    category = models.CharField(
        max_length=6,
        choices=TYPES,
        default='SYSTEM',
    )

    datatype = models.CharField(
        max_length=6,
        choices=DATATYPES,
        default='XT',
    )
    
    def __str__(self):
        return self.name

class AlternateDiagnosticName(models.Model):
    name = models.CharField(max_length=50)
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)

class MyArrayField(models.TextField):
    description = "A numpy array field serialized to txt"

    def from_db_value(self, value, expression, connection):
        return self.to_python(value)

    def to_python(self, value):
        if value is None:
            return None
        elif isinstance(value, np.ndarray):
            return value
        else:
            return np.fromstring(value, sep=' ')

    def get_prep_value(self, value):
        if value is None:
            return None
        else:
            strrep = np.array2string(value,threshold=np.inf,max_line_width=np.inf)
            return strrep[1:-1]

class TimeSeries(models.Model):
    time = MyArrayField()

class DiagnosticCalibration(models.Model):
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)
    vinput = MyArrayField()
    inputUnits = models.ForeignKey(ComboUnit, on_delete=models.CASCADE, related_name="inputUnits")
    output = MyArrayField()
    outputUnits = models.ForeignKey(ComboUnit, on_delete=models.CASCADE, related_name="outputUnits")
    resolution = models.FloatField(blank=True,null=True)
    temporalresolution = models.FloatField(blank=True,null=True)
    
    description = models.TextField()
    date = models.DateTimeField(null=True)
    expiration = models.DateField(null=True)
    datasheet = models.FileField(null=True, blank=True)

    def calibrate(self,vin):
        cal = np.interp(vin, self.vinput,self.output, left=np.nan, right=np.nan)
        return cal

class DiagnosticSetup(models.Model):
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)
    date = models.DateTimeField(null=True)
    expiration = models.DateField(null=True, blank=True)
    description = models.TextField()
    components = models.ManyToManyField("system.component", blank=True)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.diagnostic.name + str(self.date)

class DiagnosticSeries(models.Model):
    time = models.ForeignKey(TimeSeries, on_delete=models.CASCADE)
    values = MyArrayField()
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)
    run = models.ForeignKey(Run, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

    def interp(self, tnew):
        ###!!! interpolate values uniformly without nans.
        t0,vals = self.time.time, self.values
        nans = np.isnan(vals)
        return np.interp(tnew, t0[~nans], vals[~nans])

class DiagnosticFile(models.Model):
    run = models.ForeignKey(Run,on_delete=models.CASCADE)
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    file = models.FileField()

    DOCUMENT = 'DOC'
    IMAGE = 'IMG'
    VIDEO = 'VID'
    OTHER = 'OTR'
    FILETYPES = [
        (DOCUMENT, 'Document'),
        (IMAGE, 'Image'),
        (VIDEO, 'Video'),
        (OTHER, 'Other'),
    ]
    type = models.CharField(
        max_length=3,
        choices=FILETYPES,
        default=DOCUMENT,
    )
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural="diagnostic files"

stats/models.py
from django.db import models
from data.models import Run, Diagnostic, DiagnosticSeries, TimeSeries, MyArrayField
from system.models import ConditionInstance, Condition
from sklearn import linear_model

# Create your models here.

class ConditionInstanceFit(models.Model):
    instance = models.OneToOneField(ConditionInstance, on_delete=models.CASCADE)
    start = models.FloatField(null=True,blank=True)
    stable_start = models.FloatField(null=True,blank=True)
    stable_end = models.FloatField(null=True,blank=True)
    end = models.FloatField(null=True,blank=True)
    notes = models.TextField(null=True)

    def __str__(self):
        return self.instance.name + "_" + str(self.start) + "_" + str(self.end)

class RunUsage(models.Model):
    run = models.OneToOneField(Run, on_delete=models.CASCADE)
    time = models.FloatField(null=True,blank=True)
    energy = models.FloatField(null=True,blank=True)
    mass = models.FloatField(null=True,blank=True)
    notes = models.TextField(null=True)

    def __str__(self):
        return self.run.name + "_use_stats"

class DiagnosticConditionAverage(models.Model):
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE)
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)
    value = models.FloatField(null=True, blank=True)
    err = models.FloatField(null=True, blank=True)
    npoints = models.FloatField(null=True, blank=True)
    notes = models.TextField(null=True)

    def __str__(self):
        return self.condition.name + "_" + str(self.diagnostic) + "_" + str(self.value)

class SeriesStableStats(models.Model):
    series = models.ForeignKey(DiagnosticSeries, on_delete=models.CASCADE)
    condition = models.ForeignKey(ConditionInstanceFit, on_delete=models.CASCADE)
    avg = models.FloatField(null=True,blank=True)
    stdev = models.FloatField(null=True,blank=True)
    min = models.FloatField(null=True,blank=True)
    max = models.FloatField(null=True,blank=True)
    notes = models.TextField(null=True)

    def __str__(self):
        return self.series.diagnostic.name + "_" + self.condition.instance.run.name + "_" + self.condition.instance.run.test.name

class SeriesStartupStats(models.Model):
    series = models.ForeignKey(DiagnosticSeries, on_delete=models.CASCADE)
    condition = models.ForeignKey(ConditionInstanceFit, on_delete=models.CASCADE)
    dt = models.FloatField(null=True,blank=True)
    stdev = models.FloatField(null=True,blank=True)
    min = models.FloatField(null=True,blank=True)
    max = models.FloatField(null=True,blank=True)
    notes = models.TextField(null=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.series.diagnostic.name + "_" + self.condition.instance.run.name + "_" + self.condition.instance.run.test.name


class MyListField(models.TextField):
    description = "A string list serialized to txt"

    def from_db_value(self, value, expression, connection):
        return self.to_python(value)

    def to_python(self, value):
        if value is None:
            return None
        elif isinstance(value, list):
            return value
        else:
            return eval(value)

    def get_prep_value(self, value):
        if value is None:
            return None
        else:
            strrep = repr(value)
            return strrep

class LinearModel(models.Model):
    name = models.CharField(max_length=150)
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE, null=True,blank=True)
    headers = MyListField(null=True,blank=True)
    coeff = MyArrayField(null=True,blank=True)
    intercept = models.FloatField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    fit_method = models.CharField(max_length=100, null=True, blank=True)
    notes = models.TextField(null=True)

    def __str__(self):
        return self.name + "_" + str(self.updated)

    def getModelObject(self):
        reg = linear_model.LinearRegression()
        reg.coef_ = self.coeff
        reg.intercept_ = self.intercept
        return reg


class Flag(models.Model):
    run = models.ForeignKey(Run, on_delete=models.CASCADE)
    FLAGTYPES = [
        (0, 'Missing diagnostic'),
        (1, 'Missing input diagnostic'),
        (2, 'Arc unstable'),
        (3, 'Water leak'),
        (4, 'Insufficient vacuum'),
    ]
    aborted = models.BooleanField(default=False)
    rating = models.PositiveIntegerField(default=0, choices=FLAGTYPES)
    description = models.CharField(max_length=150, null=True, blank=True)
    
    def __str__(self):
        return self.rating + "_" + self.description  

data/forms.py
from django import forms
from .models import Test,Diagnostic

class SearchForm(forms.Form):
    tests = forms.ModelMultipleChoiceField(
            queryset = Test.objects.all(),
            required=False,
            )
    #sheets = forms.MultipleChoiceField(
    #        label='Sheets:',
    #        widget=forms.CheckboxSelectMultiple,
    #        choices= Sheet.objects.all()
    #        )
    diagnostics = forms.ModelMultipleChoiceField(
            queryset = Diagnostic.objects.all(),
            required=False,
            )

class UploadTestForm(forms.Form):
    name = forms.CharField(max_length=50)
    date = forms.DateField()
    file = forms.FileField()

class UploadRunForm(forms.Form):
    name = forms.CharField(max_length=50)
    file = forms.FileField()

data/templates/data/apparatus_detail.html
{% extends "base_generic.html" %}

{% block title %}<title>{{ apparatus.name }}</title>{% endblock %}

{% block content %}
  <h1>{{ apparatus.name }}</h1>
  <p><strong>Notes:</strong> {{ apparatus.notes }}</p>
  <p><a href="{% url 'upload_xlsx' apparatus.pk %}">Upload Test (*.xlsx)</a></p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Tests</h4>

    {% for test in apparatus.test_set.all %}
      <hr>
      <p><strong><a href="{% url 'test' test.pk %}">{{test.name}}</a></strong></p>
    {% endfor %}
  </div>
{% endblock %}

data/templates/data/apparatus_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Apparatus</h1>
  <p>These are the current and past versions of the mARC apparatus at NASA Ames</p>
  {% if apparatus %}
  <ul>
    {% for app in apparatus %}
      <li><a href="{% url 'apparatus-detail' app.pk %}">{{ app.name }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no apparatus in the database.</p>
  {% endif %}       
{% endblock %}

data/templates/data/cathode_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <span class="align-middle"><h1>{{ cathode.name }}</h1></span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4"><span class="align-middle"><a href="{% url 'admin:system_cathode_change' cathode.pk %}">Edit</a></span></div>
  </div>
  <hr>

  <div class="row">
    <div class="col-lg-12">
      <p><strong>Description:</strong> {{ cathode.description }}</p>
      <p><strong>Type:</strong> {{ cathode.type }}</p>
      <p><strong>Install date:</strong> {{ cathode.installed }}</p>
      <p><strong>Removal date:</strong> {{ cathode.removed }}</p>

      <p><strong>Operation time:</strong> {{ time |floatformat:"-3"}} [min]</p>
      <p><strong>Total power usage:</strong> {{ energy |floatformat:"-3"}} [MJ]</p>
      <p><strong>Total mass flow:</strong> {{ mass |floatformat:"-3" }} [kg]</p>
      <p><strong># Cathode starts:</strong> {{ cathode.run_set.count }}</p>

      <p><strong>Notes:</strong> {{ cathode.notes }}</p>
      <div style="margin-left:20px;margin-top:20px">
      </div>

      <br>
      <h3>Associated Runs:</h3>
      <table style="width:100%">
      <tr>
          <th>Run</th>
          <th>Test</th>
          <th>Date</th>
      </tr>
      {% for run in cathode.run_set.all %}
          <tr>
              <td><a href="{% url 'run-detail' run.pk %}">{{run.name}}</a></td>
              <td><a href="{% url 'test' run.test.pk %}">{{run.test.name}}</a></td>
              <td>{{run.date}}</td>
          </tr>
      {% endfor %}
      </table>
      <hr>
    </div> <!-- end col -->
  </div> <!-- end row -->
{% endblock %}

data/templates/data/condition_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row">
  <div class="col-sm-12">
    <h1>Condition: {{ condition.name }}</h1>
    <hr>
  </div></div>

  <div class="row">
    <div class="col-sm-4">
    <h3>System Settings:</h3><br>
        <p><strong>Current [A]:</strong> {{ condition.current }}</p>
        <p><strong>Plasma Gas Flow [g/s]:</strong> {{ condition.plasma_gas_flow }}, {{condition.plasma_gas}}</p>
        <p><strong>Shield Gas Flow [g/s]:</strong> {{ condition.shield_gas_flow }}, {{condition.shield_gas}}</p>
        <p><strong>Nozzle:</strong> <a href="{% url 'nozzle-detail' condition.nozzle.pk %}">{{ condition.nozzle }}</a></p>
        <p><strong># Disks:</strong> {{ condition.disks }}</p>
        <p><strong>Notes:</strong> {{ condition.notes }}</p><br>
    </div>

    <div class="col-sm-8">
    <h3>Condition Statistics:</h3>
    <table style="width:100%">
    <tr>
        <th>Diagnostic</th>
        <th>Average</th>
        <th>Stdev</th>
        <th>Count</th>
    </tr>
    {% for cond in condition.diagnosticconditionaverage_set.all %}
        <tr>
            <td>{{cond.diagnostic.name}}</td>
            <td>{{cond.value|floatformat:2}}</td>
            <td>{{cond.err|floatformat:3}}</td>
            <td>{{cond.npoints|stringformat:"d"}}</td>
        </tr>
    {% endfor %}
    </table>
    <br>
    <h3>Associated Runs:</h3>
    <table style="width:100%">
    <tr>
        <th>Test</th>
        <th>Run</th>
        <th>Date</th>
        <th>Dwell Time (s)</th>
        <th>L1 arm</th>
        <th>L2 arm</th>
        <th>Sweep arm</th>
    </tr>
    {% for cond in condition.conditioninstance_set.all %}
        <tr>
            <td><a href="{% url 'test' cond.run.test.pk %}">{{cond.run.test.name}}</a></td>
            <td><a href="{% url 'run-detail' cond.run.pk %}">{{cond.run.name}}</a></td>
            <td>{{cond.run.date}}</td>
            <td>{{cond.dwell_time}}</td>
            <td>{% for dev in cond.l1_devices.all%}dev.name,{% endfor %} {{cond.l1_insertion}} {% if cond.l1_insertion %}[s]{%endif%}</td>
            <td>{% for dev in cond.l2_devices.all%}dev.name,{% endfor %} {{cond.l2_insertion}} {% if cond.l2_insertion %}[s]{%endif%}</td>
            <td>{% for dev in cond.sweep_devices.all%}dev.name,{% endfor %} {{cond.sweep_insertion}} {% if cond.sweep_insertion %}[s]{%endif%}</td>
        </tr>
    {% endfor %}
    </table>
    <hr>
    </div><!-- End col -->
    
  </div><!-- End row -->


  <div style="margin-left:20px;margin-top:20px">
  </div>
{% endblock %}

data/templates/data/diagnostic_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ diagnostic.name }}</h1>

  <p><strong>Description:</strong> {{ diagnostic.description }}</p>
  <p><strong>Sensor:</strong> {{ diagnostic.sensor }}</p>
  <p><strong>Notes:</strong> {{ diagnostic.notes }}</p>
  <div style="margin-left:20px;margin-top:20px">
  </div>
{% endblock %}

data/templates/data/disk_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <span class="align-middle"><h1>Disk: {{ disk.name }}</h1></span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4"><span class="align-middle"><a href="{% url 'admin:system_disk_change' disk.pk %}">Edit</a></span></div>
  </div>
  <hr>

  <div class="row">
    <div class="col-lg-12">
      <p><strong>Operation time:</strong> {{ time |floatformat:"-3"}} [min]</p>
      <p><strong>Total power usage:</strong> {{ energy |floatformat:"-3"}} [MJ]</p>
      <p><strong>Total mass flow:</strong> {{ mass |floatformat:"-3" }} [kg]</p>

      <p><strong>Notes:</strong> {{ disk.notes }}</p>
      {% if disk.photo %}
        <img src="{{disk.photo.url}}" alt="{{disk.name}}">
      {% endif %}
      <div style="margin-left:20px;margin-top:20px">
      </div>

      <br>
      <h3>Associated Runs:</h3>
      <table style="width:100%">
      <tr>
          <th>Run</th>
          <th>Test</th>
          <th>Date</th>
      </tr>
      {% for run in disk.run_set.all %}
          <tr>
              <td><a href="{% url 'run-detail' run.pk %}">{{run.name}}</a></td>
              <td><a href="{% url 'test' run.test.pk %}">{{run.test.name}}</a></td>
              <td>{{run.date}}</td>
          </tr>
      {% endfor %}
      </table>
      <hr>
    </div> <!-- end col -->
  </div> <!-- end row -->
{% endblock %}

data/templates/data/facility_detail.html
{% extends "base_generic.html" %}
{% block title %}<title>{{ facility.name }}</title>{% endblock %}

{% block content %}
  <h1>Facility: {{ facility.name }}</h1>

  <p><strong>Description:</strong> {{ facility.notes }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Apparatus</h4>

    {% for app in facility.apparatus_set.all %}
      <hr>
      <p><strong><a href="{% url 'apparatus' app.pk %}">{{app.name}}</a></strong></p>
    {% endfor %}
  </div>
{% endblock %}

data/templates/data/nozzle_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <span class="align-middle"><h1>Nozzle: {{ nozzle.name }}</h1></span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4"><span class="align-middle"><a href="{% url 'admin:system_nozzle_change' nozzle.pk %}">Edit</a></span></div>
  </div>
  <hr>

  <div class="row">
    <div class="col-lg-12">
      <p><strong>Diameter [cm]:</strong> {{ nozzle.diameter }}</p>
      <p><strong>Install date:</strong> {{ nozzle.installed }}</p>

      <p><strong>Operation time:</strong> {{ time |floatformat:"-3"}} [min]</p>
      <p><strong>Total power usage:</strong> {{ energy |floatformat:"-3"}} [MJ]</p>
      <p><strong>Total mass flow:</strong> {{ mass |floatformat:"-3" }} [kg]</p>
      <p><strong>Notes:</strong> {{ nozzle.notes }}</p>
      {% if nozzle.photo %}
        <img src="{{nozzle.photo.url}}" alt="{{nozzle.name}}">
      {% endif %}
      <div style="margin-left:20px;margin-top:20px">
      </div>

      <br>
      <h3>Associated Runs:</h3>
      <table style="width:100%">
      <tr>
          <th>Run</th>
          <th>Test</th>
          <th>Date</th>
      </tr>
      {% for run in nozzle.run_set.all %}
          <tr>
              <td><a href="{% url 'run-detail' run.pk %}">{{run.name}}</a></td>
              <td><a href="{% url 'test' run.test.pk %}">{{run.test.name}}</a></td>
              <td>{{run.date}}</td>
          </tr>
      {% endfor %}
      </table>
      <hr>
    </div> <!-- end col -->
  </div> <!-- end row -->
{% endblock %}

data/templates/data/test_detail.html
{% extends "base_generic.html" %}
{% load math_tags %}
{% block title %}<title>{{ test.name }}</title>{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <span class="align-middle"><h1>Test: {{ test.name }}</h1></span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4"><span class="align-middle"><a href="{% url 'admin:data_test_change' test.pk %}">Edit</a></span></div>
  </div>
  <hr>

  <p><strong>Date:</strong> {{ test.date }}</p>
  <p><strong>Apparatus:</strong> <a href="{% url 'apparatus-detail' test.apparatus.pk %}">{{ test.apparatus.name }}</a></p>
  <p><strong>Notes:</strong> {{ test.notes }}</p>
  <p><a href="{% url 'upload_csv' test.pk %}">Upload additional run (*.csv)</a></p>


  <div style="margin-left:20px;margin-top:20px">
    <table style="width:100%">
    <tr>
        <th>Run</th>
        <th>Date</th>
        <th># Conditions</th>
        <th>Run time [s]</th>
        <th>Total energy [kJ]</th>
        <th>Total mass flow [g]</th>
        <th>Flags</th>
    </tr>
    {% for run in test.run_set.all %}
        <tr>
            <td><strong><a href="{% url 'run-detail' run.pk %}">{{run.name}}</a></strong></td>
            <td>{{run.date}}</td>
            <td>{{run.conditioninstance_set.count}}</td>
            <td>{{run.runusage.time|floatformat:1 }}</td>
            <td>{{run.runusage.energy|divide:1000|floatformat:2 }}</td>
            <td>{{run.runusage.mass|floatformat:2 }}</td>
            <td></td>
        </tr>
    {% endfor %}
    </table>
  </div>
{% endblock %}